void InsertSort(int* array, int len);
void SelectionSort(int* array, int len);
void PrintArray(int* array, int len);
void Merge(int* array, int start, int mid, int end);
void MergeSort(int *array, int len);
void RecursiveInsertSort(int* array, int len);
int CountInversion(int* array, int len);
int MergeInversion(int* array, int start, int mid, int end);
int Partition(int* array, int p, int r);
void QuickSort(int* array, int p, int r);
